language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37

sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=cd11627dca1bf785f9ef8ac4a8c7b6298e11dc6186d25e1658298c6a7075fcc8

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: tox

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: coveralls
